theme: minima
title: Autonomous Insect Light Trap
author: The Beetles - University of Wisconsin-Madison
description: Documentation for the open-source project developing an insect light trap for the Wisconsin Department of Natural Resources and ecologist Michael Miller.
